### ISSUE TITLE
(Official Server)Winter Open Server Test Announcement! January 24th-26th!

### ISSUE THREAD

**Issue by dlwh13** [tux3/LoE-PrivateServer#89]
How do you like to celebrate the new year? Either spending time with family, or partying with friends? Inclined to stay up all night one day and sleep in the next? However you spend this time of year, I personally like to celebrate it with ponies and more ponies - and now you can too! 

Tune in later this month, from the 24th to the 26th, and you'll find that the servers will be open for all of you to come in and enjoy the game! We can all have fun playing, dancing, doing quests, fighting monsters, or just sittin' in the town square with our buds. 

The new build will be available on the 22nd of January on our downloads page( http://www.legendsofequestria.com/downloads ).On the 24th, the servers will open at 12:01 AM EST and close on the 26th at 11:59 PM EST. 
We have recently created a new server system, which so far has proven to be far more secure than the previous system. This is a test of the new system. Please remember that you must have a forum account in order to log in and play the game. 

Everyone here on the team hopes to have some great fun together with you to kick off the new year, and we hope you'll join us for it! Roll on 2015!

**Comment by dlwh13** [comment]
** Download **

Hello everyone! You can now download the game in preparation for the Open Server Weekend!

The servers will open to the public at 12:01am EST on January 24th and close at 11:59pm on the 26th. The game will be available through the downloads page.  Please note that you must have a forum account before you can log in to the game. It is highly suggested that you register before the 24th, as the servers will be very busy once the weekend starts! 
If you don`t have an account already, you can register here: http://forum.legendsofequestria.com/index.php?action=register

You can see the system requirements for Legends of Equestria here: http://forum.legendsofequestria.com/index.php?topic=2189.0


//Link Blocken
Windows 32 bit: http://www.mediafire.com/download/89bx9bdamt34dft/LoE-Windows_32_2015-01-22.zip
//
If that does not work, here is a back up: http://bit.ly/15Doc2E

Windows 64 bit:  
Windows Launcher: https://drive.google.com/file/d/0B7szX7edwE5Fa3ZUUjNFLV9KWXc/view?usp=sharing
or: 
http://patches.legendsofequestria.com/Legends%20of%20Equestria%20Launcher.exe
(This will automatically download the most recent version of the game. Just push "update" and then "play" and you're good to go!) 

Mac: http://www.mediafire.com/download/js8o15dv9c6h8bc/LoE-OSX_Uni_2015-01-22.zip

Linux: 
(additional builds to follow soon)

**Comment by EpicLPer** [comment]
Backup-Downloads available here: http://dl.epiclper.at/public/LoE/2015_01/

Only providing them since I know the original ones will go down shortly again due to too much traffic.

**Comment by daniel-j** [comment]
Linux build: https://mega.co.nz/#!F10VUJJS!1VnNhH9QY_SOqiCe8fn-GU0vHdzBbiFCg62ZJp6KaD4

**Comment by JockeTF** [comment]
I'll see if I can do some captures for this version as well.

**Comment by dlwh13** [comment]
is this project still continue?

**Comment by Nuke928** [comment]
I would like to contribute, but I have no idea where to start on reverse-engineering the DLLs. Documentation is missing.

**Comment by tux3** [comment]
I'm not maintaining this project anymore.
If someone cares to send a PR or finds a security issue, I will look at it, but otherwise I'm not working on it at the moment.

@Nuke928 
There's an [awful attempt](https://github.com/tux3/LoE-PrivateServer/blob/master/moreInfos/Packets.txt) at documenting what I was doing when reverse engineering, but it's more of a personal [brain dump](https://github.com/tux3/LoE-PrivateServer/blob/master/moreInfos/Infos.txt)  than anything. 

You'll want to use something like Red Gate Reflector to look at the DLLs.

**Comment by DanielOaks** [comment]
I'm interested in contributing to this project some more. I'm gonna be grabbing captures, look into the RE and DLL side of things as well.

I'm super busy with stuff right now so I can't promise anything, but I'll do my best to update it and get it working decently with the new version and implement some new stuff. Thanks for the awesome work so far @tux3 :)

**Comment by JockeTF** [comment]
Here's a capture of a short session:

http://jocketf.se/files/.loe/captures/2015-01-22/session.pcapng

It contains the traffic for:
* Starting the game.
* Logging in.
* Running around for a few seconds.
* Logging out.
* Quitting the game.

**Comment by dlwh13** [comment]
I captured some packet too, but i can't capture the using pet
i can't find that quest

**Comment by dlwh13** [comment]
Uploading in here?
i captured some packet, but so many dummy packet
ex:)Broadcast Who has (ip)

**Comment by DanielOaks** [comment]
If you're able to post a link to Dropbox, some other service, or even just email it to [me directly](mailto:daniel@danieloaks.net), any of those should be fine.

I'm talking with someone else who's been involved with LoE private servers as well, seeing the best way we can go about this.

**Comment by Nuke928** [comment]
Well, after some fighting with the CIL instruction set I finally accomplished something. I have working DLL files that make it to the server listing. When connecting to a server it somehow gets stuck after the server echos `Set id request: 19/18`. Probably a protocol change? https://github.com/Nuke928/LoE-PrivateServer/tree/2015/patchedDLLs/January%202015

**Comment by DanielOaks** [comment]
Awesome, nice job Nuke. Yeah, they overhauled most of the protocol, from the chats I've had. So we'll essentially need to regrab everything from scratch on the game server side of things.

**Comment by EpicLPer** [comment]
The funny thing tho: They managed to f*ck it up so bad that whenever someone writes a message the client laggs for a few milliseconds.

**Comment by dlwh13** [comment]
I sent my packet to Daniel, it has so many dummy packet, sorry

**Comment by DanielOaks** [comment]
Thanks @dlwh13, got your message.

In addition, if anyone wants to / is running packet capture analysis and all, feel free to email me. I've got a decent set of captures that hopefully should be useful (stuff I personally captured, that is).

**Comment by dlwh13** [comment]
@DanielOaks Thx Daniel, I hope it can help this project

**Comment by Nuke928** [comment]
One thing that changed in the protocol is the "show characters screen" packet. I have tried to emulate this in the server and the client certainly did make it to the character selection screen. Though it gets stuck at "Loading Ponies". After that I'm afraid the client has to respond first, I am still trying to find out where the characters actually get sent to the client.

Some little analysis:

1. Connection/PNet handshake 83, 84, 85
2. Pings from both the client and server
3. Server sends 45 01. The message contains the word "Characters".
4. Client sends 86 (data ack)

At this point the character selection is loaded at the client.

I'm also suspecting that my DLL files are still not completly patched.

**Comment by dlwh13** [comment]
Server will be open (test)

Hello everyone!!

The most recent Open Server Weekend suffered from connection issues and room crashes. Despite the problems, we managed to set a new record for the most players on simultaneously; but we know that it wasn't the ideal experience we had hoped for, and that a lot of you still didn't get a chance to experience the game. Plus, these events are our opportunity to make sure everything in the game's working as intended.

To give you a bit more insight, one of the major issues we had to deal with involved a DDoS attack on our servers. What is a DDoS attack you might ask? Well, check out this cool link I stumbled upon while pondering that same question myself: http://www.digitalattackmap.com/understanding-ddos/. What follows are screenshots of the traffic we received during the DDoS attack.

http://i.imgur.com/mqN6sBD.png
http://i.imgur.com/Q7nm37I.png
http://i.imgur.com/49czBuD.png
http://i.imgur.com/xu1sRCY.png
http://i.imgur.com/vA1LCyn.png

Those inbound numbers would look really cool if this was an internet speed test. Unfortunately, that's not the case here. Those high inbound numbers mean too many fake connections were trying to reach our servers keeping out real connections (i.e. actual players) from enjoying the game. Not very fun if you ask me. We're constantly working behind the scenes addressing problems as they come up. However, we know that still doesn't change the fact that many players were left out from enjoying the last Open Server Weekend.

Therefore, to make up for those that were unable to play last Open Server Weekend, and to give us another chance to test our systems and some new fixes, we'd like to give everyone another opportunity to explore Equestria. That's why we'll be holding another Open Server Test soon, on February 20-21!

We'll make another announcement once the game client is available to download. You will be able to to install the game client on your computer prior to the Open Server Test, but remember, the servers won't be open until 12:01 AM EST on Friday, February 20th. The servers will close on Saturday, February 21st at 11:59 PM EST.

Hope to see you then!

(P.S. Here's a cool countdown. Enjoy!)

**Comment by dlwh13** [comment]
Client DL

Hello everypony!!

The Open Server Event is almost upon us! Servers open up at 12:01 AM EST on Friday January 20th (i.e. tomorrow). We hope you�re as excited as we are! To get you ready for the Open Server Event, here are the download links for the game client. Go ahead and pick the download that corresponds to your machine�s operating system and you�ll be set to enter Equestria first thing tomorrow! Just know that the game won�t let you log in until our game servers open up. Got that? Okay!

Windows (x86 / 32-bit): http://bit.ly/1DxUJp1
Windows (x64 / 64-bit): http://bit.ly/1Dy4J1F
Mac OS X: http://bit.ly/1DxUBG9
Linux: coming soon

Please Note: Your browser might inform you that the file is malicious! Don�t worry though, it�s still safe!

Take note that with each Open Server event, we enable new fixes and features. Therefore, we have to wipe game data on our servers with each update. Character data and items collected from previous Open Server events will NOT carry over.

Thanks again for all your support everyone! Next stop, Equestria!
